# Generated by Django 4.0.4 on 2022-07-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipInfoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='equipSearchClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchTag', models.CharField(max_length=90)),
            ],
        ),
    ]
