# Generated by Django 4.0.4 on 2022-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentFinder', '0002_addequipmentclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addequipmentclass',
            name='equipFile',
            field=models.FileField(blank=True, upload_to='equipDocs'),
        ),
        migrations.AlterField(
            model_name='addequipmentclass',
            name='equipImage',
            field=models.ImageField(upload_to='equipImages'),
        ),
        migrations.AlterField(
            model_name='addequipmentclass',
            name='equipLocation',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='addequipmentclass',
            name='equipName',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='addequipmentclass',
            name='tagID',
            field=models.CharField(max_length=85),
        ),
    ]
